#!/bin/sh

PATH=/sbin:/usr/sbin:/bin:/usr/bin

# firefox is set as default in his own postinst
# slaves included
# BROWSER=$(which firefox 2>/dev/null)
# if [ -x "${BROWSER}" ]; then
#     update-alternatives --set x-www-browser "${BROWSER}" >/dev/null
# fi

exit 0
