#!/bin/bash
set -e


source ./functions.sh

source_version_info
debian_changelog
cleanup_old_builds
debian_cleanup
debian_foo_basics
basic_control common
debian_rules

# debian

sed -e "s/\@CODENAME_SAFE\@/${CODENAME_SAFE}/g" \
    -e "s/\@FLAVOUR\@/${FLAVOUR}/g" \
    ./debtemplate/copyright \
    > ./debian/copyright

sed -e "s/\@CODENAME_SAFE\@/${CODENAME_SAFE}/g" \
    -e "s/\@DISPLAY\@/${DISPLAY}/g" \
    ./debtemplate/get-template \
    > ./debian/get-template
chmod 755 ./debian/get-template

sed -e "s/\@CODENAME_SAFE\@/${CODENAME_SAFE}/g" \
    -e "s/\@DISPLAY\@/${DISPLAY}/g" \
    ./debtemplate/livesettings.install \
    > ./debian/${CODENAME_SAFE}-common-livesettings.install
sed -e "s/\@CODENAME_SAFE\@/${CODENAME_SAFE}/g" \
    -e "s/\@DISPLAY\@/${DISPLAY}/g" \
    ./debtemplate/livesettings.lintian-overrides \
    > ./debian/${CODENAME_SAFE}-common-livesettings.lintian-overrides
sed -e "s/\@CODENAME_SAFE\@/${CODENAME_SAFE}/g" \
    -e "s/\@DISPLAY\@/${DISPLAY}/g" \
    ./debtemplate/livesettings.postinst \
    > ./debian/${CODENAME_SAFE}-common-livesettings.postinst
sed -e "s/\@CODENAME_SAFE\@/${CODENAME_SAFE}/g" \
    -e "s/\@DISPLAY\@/${DISPLAY}/g" \
    ./debtemplate/livesettings.preinst \
    > ./debian/${CODENAME_SAFE}-common-livesettings.preinst
sed -e "s/\@CODENAME_SAFE\@/${CODENAME_SAFE}/g" \
    -e "s/\@DISPLAY\@/${DISPLAY}/g" \
    ./debtemplate/livesettings.service \
    > ./debian/${CODENAME_SAFE}-common-livesettings.service

sed -e "s/\@CODENAME_SAFE\@/${CODENAME_SAFE}/g" \
    -e "s/\@DISPLAY\@/${DISPLAY}/g" \
    ./debtemplate/settings.install \
    > ./debian/${CODENAME_SAFE}-common-settings.install
sed -e "s/\@CODENAME_SAFE\@/${CODENAME_SAFE}/g" \
    -e "s/\@DISPLAY\@/${DISPLAY}/g" \
    ./debtemplate/settings.postinst \
    > ./debian/${CODENAME_SAFE}-common-settings.postinst

## template
[ -d etc ] && rm -r etc
[ -d live ] && rm -r live
[ -d sbin ] && rm -r sbin
[ -d usr ] && rm -r usr

cp -a templates/common .

# debian settings common
# ======================


sed -e "s/\@CODENAME_SAFE\@/${CODENAME_SAFE}/g" \
    -e "s/\@DISPLAY\@/${DISPLAY}/g" \
    ./template/livesettings \
    > ./livesettings
sed -e "s/\@FLL_LIVE_USER\@/${FLL_LIVE_USER}/g" \
    -e "s/\@DISPLAY\@/${DISPLAY}/g" \
    ./template/live/etc/polkit-1/localauthority/10-vendor.d/10-live-cd.pkla \
    > ./live/etc/polkit-1/localauthority/10-vendor.d/10-live-cd.pkla
sed -e "s/\@FLL_LIVE_USER\@/${FLL_LIVE_USER}/g" \
    -e "s/\@DISPLAY\@/${DISPLAY}/g" \
    template/live/etc/systemd/system/getty@tty1.service \
    > live/etc/systemd/system/getty@tty1.service


exit 0
