#!/bin/bash
set -e


[ -e ../template/zfunctions.sh ] && source ../template/zfunctions.sh

source_version_info
debian_changelog
cleanup_old_builds
debian_cleanup
debian_foo_basics
basic_control common
debian_rules

# debian

sed -e "s/\@CODENAME_SAFE\@/${CODENAME_SAFE}/g" \
    ../template/debian/copyright \
    > ./debian/copyright

sed -e "s/\@CODENAME_SAFE\@/${CODENAME_SAFE}/g" \
    -e "s/\@CODENAME\@/${CODENAME}/g" \
    ../template/debian/${CODENAME_SAFE}-common-livesettings.install \
    > ./debian/${CODENAME_SAFE}-common-livesettings.install

sed -e "s/\@CODENAME_SAFE\@/${CODENAME_SAFE}/g" \
    -e "s/\@CODENAME\@/${CODENAME}/g" \
    ../template/debian/${CODENAME_SAFE}-common-livesettings.lintian-overrides \
    > ./debian/${CODENAME_SAFE}-common-livesettings.lintian-overrides

sed -e "s/\@CODENAME_SAFE\@/${CODENAME_SAFE}/g" \
    -e "s/\@CODENAME\@/${CODENAME}/g" \
    ../template/debian/${CODENAME_SAFE}-common-livesettings.postinst \
    > ./debian/${CODENAME_SAFE}-common-livesettings.postinst

sed -e "s/\@CODENAME_SAFE\@/${CODENAME_SAFE}/g" \
    -e "s/\@CODENAME\@/${CODENAME}/g" \
    ../template/debian/${CODENAME_SAFE}-common-livesettings.preinst \
    > ./debian/${CODENAME_SAFE}-common-livesettings.preinst

sed -e "s/\@CODENAME_SAFE\@/${CODENAME_SAFE}/g" \
    -e "s/\@CODENAME\@/${CODENAME}/g" \
    ../template/debian/${CODENAME_SAFE}-common-livesettings.service \
    > ./debian/${CODENAME_SAFE}-common-livesettings.service

sed -e "s/\@CODENAME_SAFE\@/${CODENAME_SAFE}/g" \
    -e "s/\@CODENAME\@/${CODENAME}/g" \
    ../template/debian/${CODENAME_SAFE}-common-settings.install \
    > ./debian/${CODENAME_SAFE}-common-settings.install

sed -e "s/\@CODENAME_SAFE\@/${CODENAME_SAFE}/g" \
    -e "s/\@CODENAME\@/${CODENAME}/g" \
    ../template/debian/${CODENAME_SAFE}-common-settings.postinst \
    > ./debian/${CODENAME_SAFE}-common-settings.postinst

## template
[ -d etc ] && rm -r etc
[ -d live ] && rm -r live
[ -d sbin ] && rm -r sbin
[ -d usr ] && rm -r usr

cp -a ../template/etc .
cp -a ../template/live .
cp -a ../template/sbin .
cp -a ../template/usr .

sed -e "s/\@CODENAME_SAFE\@/${CODENAME_SAFE}/g" \
    -e "s/\@CODENAME\@/${CODENAME}/g" \
    ../template/livesettings \
    > ./livesettings
sed -e "s/\@FLL_LIVE_USER\@/${FLL_LIVE_USER}/g" \
    -e "s/\@CODENAME\@/${CODENAME}/g" \
    ../template/live/etc/polkit-1/localauthority/10-vendor.d/10-live-cd.pkla \
    > ./live/etc/polkit-1/localauthority/10-vendor.d/10-live-cd.pkla
sed -e "s/\@FLL_LIVE_USER\@/${FLL_LIVE_USER}/g" \
    -e "s/\@CODENAME\@/${CODENAME}/g" \
    ../template/live/etc/systemd/system/getty@tty1.service \
    > live/etc/systemd/system/getty@tty1.service


exit 0
