#!/bin/sh
# script for live-settings

set -e

if [ -f /etc/default/distro ]; then
    . /etc/default/distro
fi

all_users_common_settings() {
    # we run all users settings
    if [ -f /usr/share/${CODENAME_SAFE}-common-livesettings/all-users-settings ] ;then
        /usr/share/${CODENAME_SAFE}-common-livesettings/all-users-settings
    fi
}

gen_adduser_conf() {
    sed -i 's/^DIR_MODE=.*/DIR_MODE=0700/' /etc/adduser.conf

    unset GROUPS
    for g in ${FLL_LIVE_USER_GROUPS}; do
        if getent group ${g} >/dev/null; then
            GROUPS="${GROUPS} ${g}"
        fi
    done

    sed -i -e 's/^#\?\(EXTRA_GROUPS=\).*/\1"'"${GROUPS# }"'"/' \
           -e 's/^#\?\(ADD_EXTRA_GROUPS=\).*/\11/' \
            /etc/adduser.conf
}

add_live_user() {
    rm -f /etc/skel/.face.icon
    adduser --comment ${FLL_LIVE_USER} ${FLL_LIVE_USER} \
<< EOF
live
live
EOF
}

user_home_common_settings() {
    if [ -f /usr/share/${CODENAME_SAFE}-common-livesettings/user-home-settings ] ;then
        su "${FLL_LIVE_USER}" -c /usr/share/${CODENAME_SAFE}-common-livesettings/user-home-settings
    fi
}


hack_bashrc() {
    grep -s -q 'alias su' /home/${FLL_LIVE_USER}/.bashrc && return 0
    printf "\nalias su='sudo su'\n" \
        >> /home/${FLL_LIVE_USER}/.bashrc
    chown ${FLL_LIVE_USER}:${FLL_LIVE_USER} /home/${FLL_LIVE_USER}/.bashrc
    
    # Set eye-friendly color palette
    for userbash in "/root/.bashrc" "/home/${FLL_LIVE_USER}/.bashrc"; do
        cat <<-EOF >> ${userbash}
        
        # Eye-friendly color palette
        echo -en "\e]P0181818" # black
        echo -en "\e]P1A12525" # darkred
        echo -en "\e]P24E9A06" # darkgreen
        echo -en "\e]P3C4A000" # brown
        echo -en "\e]P41A5AAA" # darkblue
        echo -en "\e]P575507B" # darkmagenta
        echo -en "\e]P606989A" # darkcyan
        echo -en "\e]P7D3D7CF" # lightgrey
        echo -en "\e]P8557533" # darkgrey
        echo -en "\e]P9F03232" # red
        echo -en "\e]PA8AE234" # green
        echo -en "\e]PBFCE94F" # yellow
        echo -en "\e]PC2B7DDD" # blue
        echo -en "\e]PDAD7FA8" # magenta
        echo -en "\e]PE34E2E2" # cyan
        echo -en "\e]PFFFF7DD" # white
        clear # new background
        
        EOF
    done
}

setup_calamares() {
    mkdir -p /home/${FLL_LIVE_USER}/Desktop
    if [ -e /usr/share/siduction/calamares.desktop ]; then
        cp -f /usr/share/siduction/calamares.desktop /home/${FLL_LIVE_USER}/Desktop
	cp -f /usr/share/siduction/calamares.desktop /usr/share/applications/
	#sed -i 's/pkexec calamares/sudo -E calamares/' /home/${FLL_LIVE_USER}/Desktop/calamares.desktop
        chmod +x /home/${FLL_LIVE_USER}/Desktop/calamares.desktop
    fi
    if [ -e /usr/share/siduction/chroot-helper.desktop ]; then
	cp -f /usr/share/siduction/chroot-helper.desktop /home/${FLL_LIVE_USER}/Desktop
	chmod +x /home/${FLL_LIVE_USER}/Desktop/chroot-helper.desktop
    fi
}

chown_user_dir() {
    # central point setting the ownership of users home
    ln -s /home/${FLL_LIVE_USER}/.face /home/${FLL_LIVE_USER}/.face.icon
    chown -R ${FLL_LIVE_USER}:${FLL_LIVE_USER} /home/${FLL_LIVE_USER}
}


case "$1" in
    configure)
    all_users_common_settings
    if [ -d /home/${FLL_LIVE_USER} ]; then
        echo "                                     "
        echo "*************************************"
        echo "                                     "
        echo " Something went terrible wrong:      "
        echo "  /home/$FLL_LIVE_USER exist!        "
        echo " That should not be, please check    "
        echo " involved packages and pyfll.        "
        echo " This dir must not be created by     "
        echo " somehow or somewhat - only adduser  "
        echo " should do so.                       "
        echo "                                     "
        echo "*************************************"
        echo "                                     "
        exit 1
    fi
    gen_adduser_conf
    add_live_user
    setup_calamares
    hack_bashrc
    user_home_common_settings
    chown_user_dir
    ;;
    *)
        echo "livesettings  called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac


exit 0
